#!/bin/sh /etc/rc.common

START=99
LOGGER_PROMPT="SecondStage"
. /root/updater/common.sh

start() {
    log "Second stage complete!"
    log "Starting final stage.."

    chmod +x /root/setup/setup_notify.sh
    /root/setup/setup_notify.sh
}
