#!/bin/sh

LOGGER_PROMPT="SecondStage"

set -e
set -o pipefail

# save stdout and stderr to file 
# descriptors 3 and 4, 
# then redirect them to upgrade.log
exec 3>&1 4>&2 >>/root/upgrade_output.log 2>&1

# log "Sleeping for 2mins.."
# sleep 120

# log "Starting second stage.."

PACKAGES=$(cat $HOOKSDIR/stage1-packages.list | tr '\n' ' ')
log "Installing packages: $PACKAGES"
opkg update
opkg install $PACKAGES

rm $HOOKSDIR/stage1-packages.list

log "Enabling openssh.."
/etc/init.d/dropbear disable
/etc/init.d/sshd enable

log "Enabling vnstat_backup.."
/etc/init.d/vnstat_backup restore
/etc/init.d/vnstat_backup enable

log "Enabling netbeat.."
/etc/init.d/netbeat enable

sync

scheduleReboot
