#!/bin/sh /etc/rc.common

log() {
    logger -t "First Stage" $*
}

START=99
STOP=99

start() {
    log "First stage complete.."
    log "Preparing second stage.."

    chmod +x /root/second_stage.sh
    /root/second_stage.sh
}
