#!/bin/sh /etc/rc.common

START=99
LOGGER_PROMPT="FirstStage"
. /root/updater/logger.sh 

start() {
    log "First stage complete!"
    log "Starting second stage.."

    chmod +x /root/setup/second_stage.sh
    /root/setup/second_stage.sh
}
