#!/bin/sh /etc/rc.common

log() {
	echo "[$(date)] [SecondStage] $*" >> /root/upgrade.log
}

START=99

start() {
    log "Second stage complete!"
    log "Starting final stage.."

    chmod +x /root/setup/setup_notify.sh
    /root/setup/setup_notify.sh
}
