#!/bin/sh /etc/rc.common

START=99
LOGGER_PROMPT="LiftOff"
. /root/updater/common.sh

start() {
    log "Lift off complete.."
    log "Preparing first stage.."

    chmod +x /root/setup/first_stage.sh
    /root/setup/first_stage.sh
}
